In [4]:
#Numpy常用数据结构
#1. 数组创建
# 导入库
import numpy as np
arr1 = np.array([-9,7,4,3])
arr1
arr2 = np.array([-9,7,4,3],dtype =float)# 尝试改变为int或者str
print(arr2)
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3
# 使用其他函数创建数组
np.arange(0,10,1)   
np.linspace(1,10,10)
np.zeros([4,5])
np.ones([2,3])  
arr3 + 1 #矩阵运算

[-9.  7.  4.  3.]


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [23]:
arr2 = np.array([-9,7,4,3],dtype =float)# 尝试改变为int或者str
print(arr2)

[-9.  7.  4.  3.]


In [5]:
np.arange(0,10,1)  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones([2,3]) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
#2. 数组方法
# 查看数组维度
arr3.ndim 
arr3.shape
arr3.size
arr3.dtype
arr3 + 1 #矩阵运算
arr3 /2
data2 = ((8.5,6,4.1,2,0.7),(1.5,3,5.4,7.3,9),(3.2,4.5,6,3,9),(11.2,13.4,15.6,17.8,19))
arr2 = np.array(data2)
arr2
arr2[2] #访问第三行，可以理解为行索引
arr2[2,1] #访问第三行，可以理解为行索引
arr2[:,2:4] #访问第三列
arr2[1:3] #2行和3行
arr2[1:,2:] #第2行到最后一行，第3列到最后一列
arr2[2,1] #访问第三行，第二个元素,第一个是行索引，第二个是列索引
arr2[2][1] #访问第三行，第二个元素,第一个是行索引，第二个是列索引

4.5

In [31]:
arr3.ndim 

2

In [32]:
arr3.shape

(3, 4)

In [33]:
arr3.size

12

In [34]:
arr3.dtype

dtype('int32')

In [35]:
arr3 + 1 #矩阵运算

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [36]:
arr3 /2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [37]:
arr2[2,1] #访问第三行，可以理解为行索引

4.5

In [39]:
arr3[2][1] #访问第三行，第二个元素,第一个是行索引，第二个是列索引

10

In [40]:
#3. Numpy常用数据清洗函数
#排序
#降序建议用sorted函数
s  = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])
np.sort(s)
sorted(s,reverse =True)#降序
arr1 = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])
arr1
np.sort(arr1)
np.sort(arr1,axis = 0) # 0代表沿着行的方向， 1代表沿着列的方向
np.sort(arr1,axis = 1)
argsort#返回的是排完序以后，在原数据中的索引位置
#返回的是数据中,从小到大的索引值
s = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])
np.argsort(s) 
np.where和np.extract
np.where(s>3,1,-1)# 满足条件的，赋值为3，不满足的赋值为-1，返回的数据长度和s一样
np.extract #只会输出满足条件的数据
np.extract(s>3,s)# 只输出满足条件的数据

NameError: name 'argsort' is not defined

In [43]:
s  = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])
np.sort(s)

array([1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [44]:
sorted(s,reverse =True)#降序

[8, 7, 6, 5, 4, 4, 4, 4, 3, 3, 2, 2, 2, 2, 1, 1]

In [45]:
arr1 = np.array([[0,1,3],[4,2,9],[4,5,9],[1,-3,4]])
arr1

array([[ 0,  1,  3],
       [ 4,  2,  9],
       [ 4,  5,  9],
       [ 1, -3,  4]])

In [46]:
np.sort(arr1)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  9],
       [-3,  1,  4]])

In [48]:
np.sort(arr1,axis = 0) # 0代表沿着列的方向， 1代表沿着行的方向

array([[ 0, -3,  3],
       [ 1,  1,  4],
       [ 4,  2,  9],
       [ 4,  5,  9]])

In [49]:
np.sort(arr1,axis = 1)

array([[ 0,  1,  3],
       [ 2,  4,  9],
       [ 4,  5,  9],
       [-3,  1,  4]])

In [55]:
#argsort返回的是排完序以后，在原数据中的索引位置
#返回的是数据中,从小到大的索引值
s = np.array([1,2,3,4,3,1,2,2,4,6,7,2,4,8,4,5])
print(s)

[1 2 3 4 3 1 2 2 4 6 7 2 4 8 4 5]


In [57]:
np.sort(s)

array([1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [54]:
np.argsort(s) 

array([ 0,  5,  1,  6,  7, 11,  2,  4,  3,  8, 12, 14, 15,  9, 10, 13],
      dtype=int64)

In [58]:
#np.where和np.extract
np.where(s>3,1,-1)# 满足条件的，赋值为1，不满足的赋值为-1，返回的数据长度和s一样

array([-1, -1, -1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1])

In [59]:
#np.extract 只会输出满足条件的数据
np.extract(s>3,s)# 只输出满足条件的数据

array([4, 4, 6, 7, 4, 8, 4, 5])

In [61]:
#4. Pandas常用数据结构
#series序列
import pandas as pd
import numpy as np
# 构造序列
series1 = pd.Series([2.8,3.01,8.99,8.59,5.18])
series2 = pd.Series([2.8,3.01,8.99,8.59,5.18],index = ['a','b','c','d','e'],name ='这是一个series')
series3 = pd.Series({'北京':2.8,'上海':3.01,'广东':8.99,'江苏':8.59,'浙江':5.18})


In [62]:
#series方法
series2.values

array([2.8 , 3.01, 8.99, 8.59, 5.18])

In [63]:
series3.index

Index(['北京', '上海', '广东', '江苏', '浙江'], dtype='object')

In [64]:
#dafaframe
# 构造数据框
#数据框其实就是一个二维表结构，是数据分析中，最常用的数据结构
list1 = [['张三',23,'男'],['李四',27,'女'],['王二',26,'女']]#使用嵌套列表
df1 = pd.DataFrame(list1,columns=['姓名','年龄','性别'])
type(df1)
df2 = pd.DataFrame({'姓名':['张三','李四','王二'],'年龄':[23,27,26],'性别':['男','女','女']}) #使用字典,字典的键被当成列名
df2
array1 = np.array([['张三',23,'男'],['李四',27,'女'],['王二', 26,'女']]) #使用numpy
df3 = pd.DataFrame(array1,columns=['姓名','年龄','性别'],index = ['a','b','c'] )
#dataframe方法
df2.values
df2.index
df2.columns
df2.dtypes
df2.ndim
df2.size

9

In [65]:
type(df1)

pandas.core.frame.DataFrame

In [66]:
df2 = pd.DataFrame({'姓名':['张三','李四','王二'],'年龄':[23,27,26],'性别':['男','女','女']}) #使用字典,字典的键被当成列名
df2


姓名  年龄 性别
0  张三  23  男
1  李四  27  女
2  王二  26  女

In [67]:
array1 = np.array([['张三',23,'男'],['李四',27,'女'],['王二', 26,'女']]) #使用numpy
df3 = pd.DataFrame(array1,columns=['姓名','年龄','性别'],index = ['a','b','c'] )
print(df3)

   姓名  年龄 性别
a  张三  23  男
b  李四  27  女
c  王二  26  女


In [68]:
#dataframe方法
df2.values


array([['张三', 23, '男'],
       ['李四', 27, '女'],
       ['王二', 26, '女']], dtype=object)

In [69]:
df2.index


RangeIndex(start=0, stop=3, step=1)

In [70]:
df2.columns


Index(['姓名', '年龄', '性别'], dtype='object')

In [71]:
df2.dtypes


姓名    object
年龄     int64
性别    object
dtype: object

In [72]:
df2.ndim


2

In [73]:
df2.size

9